name: Build Push Image
on: 
  workflow_dispatch:
    inputs:
      murmur-release:
        description: 'Mumble release version:'     
        required: true
      tags:
        description: 'Test scenario tags'  

jobs:
  docker-mumble-server:
    runs-on: ubuntu-latest
    name: A job to build a mumble server docker container
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64
          push: true
          tags: |
            mindlesstux/mumble:${{ github.event.inputs.murmur-release }}
